name: run-test
on: 
  workflow_dispatch:
    inputs:
      caption:
        description: "Workflow caption:"
        required: false
        default: "HELLO WORLD!"
jobs:
  my-job:
  caption:${{ github.event.inputs.caption }}
